version: "3.8"

services:
  myportfolio:
    build:
      context: .
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - backend

  mysql:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: jonasal/nginx-certbot
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - CERTBOT_EMAIL=your-email@example.com
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
    networks:
      - backend

volumes:
  db_data:
  nginx_secrets:

networks:
  backend:
